### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Zumbalamambo** [zZyan/race_gender_recognition#1]
can you please share the pretrained model?

**Comment by zZyan** [comment]
Hi,

You could find the pre-trained model from FaceNet github repo.[https://github.com/davidsandberg/facenet](here)

**Comment by EYcab** [comment]
@zZyan ,Could you please share your pre-train model?
I have been running into errors based on the models from facenet and the like of my own.
![image](https://user-images.githubusercontent.com/11568206/51692297-92d16f80-2037-11e9-8257-c101a468fbba.png)
