### ISSUE TITLE
make_features.py

### ISSUE THREAD

**Issue by happyforever123** [zZyan/race_gender_recognition#2]
Hi,
From the README.md, there is a make_features.py, which can turn UTKFace into tfrecords. However, I don't see it in your files. Can you upload it? Thanks a lot!

**Comment by TengFei75882341** [comment]
The same question , Thanks a lot!!!

**Comment by zZyan** [comment]
Sorry for the late reply. Unfortunately, the output tfrecord files are huge and I can't upload them here.

**Comment by TengFei75882341** [comment]
Hi,
It isn't the tfrecord files,it is the make_features.py file who makes the tfrecord,
you can't upload the file,thanks.

**Comment by zZyan** [comment]
sorry for the delay, just uploaded.
